name: cargo

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"
          - "x86_64-unknown-linux-musl"
          - "x86_64-pc-windows-msvc"
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy, rustfmt
          target: ${{ matrix.target }}
          default: true

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: build (release)
        uses: actions-rs/cargo@v1
        with:
          command: b
          args: -r
      - name: test (release)
        uses: actions-rs/cargo@v1
        with:
          command: t
          args: -r
