name: cargo

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: toolchain
        uses: actions-rs/toolchain@v1

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: build (release)
        uses: actions-rs/cargo@v1
        with:
          command: b
          args: -r
      - name: test (release)
        uses: actions-rs/cargo@v1
        with:
          command: t
          args: -r
